Revert "Fix `callLater` typing by passing keyword arguments"
Twisted doesn't accept keyword arguments for this function[0] as far as
I can tell. Updating to Pika 1.4.2 has caused Fedora's pika
applications, which use Twisted, to start crashing with:

  File "pika/adapters/twisted_connection.py", line 1152, in _adapter_call_later
    self._reactor.callLater(delay=delay, callable=callback)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncioSelectorReactor.callLater() missing 2 required positional arguments: 'seconds' and 'f'

[0] https://github.com/twisted/twisted/blob/twisted-26.4.0/src/twisted/internet/base.py#L947

This reverts commit 79efa4903a40bab07cbda32e830dfa0f52b5a17f.